//! Script execution and accessors for PastaLuaRuntime.
//!
//! This file contains the `impl PastaLuaRuntime` methods for executing Lua
//! scripts and the read-only accessors (split impl pattern).

use super::PastaLuaRuntime;
use crate::debug::SourceMode;
use crate::debug::source_map::SourceMap;
use crate::loader::PastaConfig;
use crate::logging::PastaLogger;
use mlua::{Lua, Result as LuaResult, Table, Value};
use std::path::Path;
use std::sync::Arc;

impl PastaLuaRuntime {
    /// Execute a Lua script string.
    ///
    /// # Arguments
    /// * `script` - Lua code to execute
    ///
    /// # Returns
    /// * `Ok(Value)` - Execution result
    /// * `Err(e)` - Execution error
    ///
    /// # Safety (input source analysis)
    /// All callers of `exec()` pass either:
    /// - Transpiled Lua code generated by `LuaTranspiler` from validated `.pasta` files
    /// - Hardcoded Rust string literals in test code
    ///   No external user input is passed directly to this method.
    ///   Errors are propagated via `LuaResult`, not unwrapped.
    pub fn exec(&self, script: &str) -> LuaResult<Value> {
        self.lua.load(script).eval()
    }

    /// Execute a Lua script string under an explicit chunk name (the `source`
    /// reported to the debugger).
    ///
    /// Identical to [`exec`](Self::exec) but sets the chunk name so a debugger
    /// breakpoint keyed on that source (the generated `.lua` name) matches. The
    /// transpiled-module load path already names its chunks; this is the analogous
    /// entry point for ad-hoc / per-request script execution under a known source.
    ///
    /// # Safety (input source analysis)
    /// Same as [`exec`](Self::exec): callers pass transpiled Lua or Rust string
    /// literals; no external user input reaches this method. Errors propagate via
    /// `LuaResult`.
    pub fn exec_named(&self, script: &str, name: &str) -> LuaResult<Value> {
        self.lua.load(script).set_name(name).eval()
    }

    /// The bound DAP listen address when the debug backend is active, else `None`.
    ///
    /// `Some(addr)` only when this runtime was built with `config.debug.enabled`
    /// and the transport bound a port (the OS-assigned concrete port is readable
    /// here even when port 0 was requested — R3.1). On the disabled default path
    /// this is always `None` (no port is ever opened — R5.5), which doubles as the
    /// zero-cost assertion hook for tests.
    pub fn debug_local_addr(&self) -> Option<std::net::SocketAddr> {
        self.debug_handle.as_ref().and_then(|h| h.local_addr())
    }

    /// Whether the debug backend is active for this runtime (a handle is held).
    pub fn debug_enabled(&self) -> bool {
        self.debug_handle.is_some()
    }

    /// The aggregated `.pasta`↔`.lua` source map held at runtime scope, or `None`.
    ///
    /// `Some` only when debugging was ENABLED at VM init and the loader built and
    /// handed the map to the enable path (task 4.4 / requirement 3.1). On the
    /// disabled (default) zero-cost path this is always `None` — no map is built
    /// (requirement 7.1). The returned `Arc` is a cheap refcount clone of the same
    /// immutable map the debug backend wiring consumes.
    pub fn debug_source_map(&self) -> Option<Arc<SourceMap>> {
        self.source_map.clone()
    }

    /// The resolved source-presentation mode for the active debug session, or
    /// `None` when debugging is disabled.
    ///
    /// Reflects the precedence `DAP attach 引数 > env > pasta.toml [debug]
    /// present_as > 既定 .pasta` resolved into `config.debug.source_mode`
    /// (requirements 6.1 / 6.3). Reads from the held [`crate::debug::DebugHandle`]
    /// so it mirrors exactly what `enable` was configured with.
    pub fn debug_source_mode(&self) -> Option<SourceMode> {
        self.debug_handle.as_ref().map(|h| h.config().source_mode)
    }

    /// Execute a Lua script from a file.
    ///
    /// # Arguments
    /// * `path` - Path to the Lua script file
    ///
    /// # Returns
    /// * `Ok(Value)` - Execution result
    /// * `Err(e)` - File read or execution error
    ///
    /// # Safety (input source analysis)
    /// The file is read from a trusted local path supplied by Rust caller code.
    /// Delegates to `exec()` which propagates errors via `LuaResult`.
    pub fn exec_file(&self, path: &Path) -> LuaResult<Value> {
        let script =
            std::fs::read_to_string(path).map_err(|e| mlua::Error::ExternalError(Arc::new(e)))?;
        self.exec(&script)
    }

    /// Get a reference to the internal Lua instance.
    ///
    /// This allows advanced operations on the Lua VM.
    pub fn lua(&self) -> &Lua {
        &self.lua
    }

    /// Get a clone of the Arc-wrapped logger, if any.
    ///
    /// This allows sharing the logger with GlobalLoggerRegistry
    /// for log routing in multi-instance scenarios.
    pub fn logger(&self) -> Option<Arc<PastaLogger>> {
        self.logger.clone()
    }

    /// Get reference to PastaConfig if available.
    ///
    /// Returns the configuration loaded from pasta.toml during PastaLoader::load().
    ///
    /// # Returns
    /// * `Some(&PastaConfig)` - Config was set during load
    /// * `None` - Config not available (e.g., runtime created without loader)
    pub fn config(&self) -> Option<&PastaConfig> {
        self.config.as_ref()
    }

    /// Register a custom module with the runtime.
    ///
    /// # Arguments
    /// * `name` - Module name (e.g., "@my_module")
    /// * `module` - Module table
    ///
    /// # Returns
    /// * `Ok(())` - Module registered successfully
    /// * `Err(e)` - Registration failed
    pub fn register_module(&self, name: &str, module: Table) -> LuaResult<()> {
        let package: Table = self.lua.globals().get("package")?;
        let loaded: Table = package.get("loaded")?;
        loaded.set(name, module)?;
        Ok(())
    }
}
