//! Lua Transpiler for Pasta DSL.
//!
//! This module provides the main transpiler interface for converting
//! Pasta AST to Lua code.

use pasta_core::registry::SceneRegistry;
use pasta_dsl::parser::{ActorScope, FileItem, GlobalSceneScope, KeyWords, PastaFile};

use super::code_gen::LuaCodeGenerator;
use super::code_gen::source_map::SourceMapSink;
use super::config::TranspilerConfig;
use super::context::TranspileContext;
use super::error::TranspileError;
use super::normalize::{LineShift, normalize_output_with_shift};

use std::io::Write;

/// Lua transpiler for Pasta DSL.
///
/// Converts Pasta AST to Lua source code.
pub struct LuaTranspiler {
    /// Transpiler configuration
    config: TranspilerConfig,
}

impl Default for LuaTranspiler {
    fn default() -> Self {
        Self::new(TranspilerConfig::default())
    }
}

impl LuaTranspiler {
    /// Create a new transpiler with the given configuration.
    pub fn new(config: TranspilerConfig) -> Self {
        Self { config }
    }

    /// Create a transpiler with default configuration.
    pub fn with_defaults() -> Self {
        Self::default()
    }

    /// Transpile PastaFile to Lua code (MAJOR-2).
    ///
    /// Processes FileItems in document order, accumulating file attributes
    /// and generating code for actors and scenes.
    ///
    /// # Arguments
    /// * `file` - The parsed PastaFile AST
    /// * `writer` - Output writer
    ///
    /// # Returns
    /// * `Ok(TranspileContext)` - Transpilation successful, context contains registries
    /// * `Err(TranspileError)` - Transpilation failed
    ///
    /// # Post-processing
    /// - Output is normalized: trailing blank lines removed, ends with exactly one newline
    ///
    /// # Source-map seam (Requirements 1.1, 3.1, 7.1)
    ///
    /// This is the thin, sink-less wrapper around [`transpile_with_sink`](Self::transpile_with_sink).
    /// It is the production transpile path: no source-map sink is attached, so the
    /// `code_gen` recording seam is inert and the generated `.lua` bytes are unchanged
    /// (Requirement 7.1, byte-invariant when source-map generation is disabled).
    pub fn transpile<W: Write>(
        &self,
        file: &PastaFile,
        writer: &mut W,
    ) -> Result<TranspileContext, TranspileError> {
        self.transpile_with_sink(file, writer, None)
    }

    /// Transpile PastaFile to Lua code, optionally recording into a source-map sink.
    ///
    /// This is the source-map receiving port (design.md "TranspileSinkPort"): it threads
    /// an optional `&mut dyn SourceMapSink` into the [`LuaCodeGenerator`] so the production
    /// loader can attach a recording sink. When `sink` is `Some`, the generator records
    /// `(generated_lua_line -> .pasta span)` correspondences for span-bearing constructs
    /// (Requirement 1.1) into the caller-owned, in-memory sink (Requirement 3.1, no
    /// mandatory intermediate file). When `sink` is `None` the seam is inert and the
    /// generated bytes are byte-identical to the sink-less path (Requirement 7.1).
    ///
    /// `code_gen` does not depend on `debug`: the sink is the always-compiled
    /// `code_gen::source_map::SourceMapSink` trait, preserving the `debug -> code_gen`
    /// dependency direction.
    ///
    /// # Arguments
    /// * `file` - The parsed PastaFile AST
    /// * `writer` - Output writer
    /// * `sink` - Optional source-map recording sink (production loader attaches one)
    pub fn transpile_with_sink<W: Write>(
        &self,
        file: &PastaFile,
        writer: &mut W,
        sink: Option<&mut dyn SourceMapSink>,
    ) -> Result<TranspileContext, TranspileError> {
        // The `LineShift` is only needed by the source-map build path
        // (`transpile_with_source_map`); the sink-bearing/sink-less callers here
        // discard it. The output bytes are identical either way (see
        // `transpile_with_source_map` for the byte-safety argument).
        let (context, _shift) = self.transpile_with_source_map(file, writer, sink)?;
        Ok(context)
    }

    /// Transpile PastaFile to Lua code, recording into a source-map sink and
    /// returning the normalize [`LineShift`] (source-map build path).
    ///
    /// This is the loader-side integration entry for `pasta-source-map` task 4.3:
    /// it is the SAME code-generation + normalize pipeline as
    /// [`transpile_with_sink`](Self::transpile_with_sink), but it additionally
    /// returns the [`LineShift`] produced by output normalization so the loader can
    /// rebase the sink's pre-normalize records onto the final `.lua` line numbers
    /// (`MapBuilderSink::finish(&shift)` — Requirement 2.1) and complete the
    /// per-chunk [`crate::debug::source_map::ChunkSourceMap`].
    ///
    /// # Byte-invariance (Requirement 7.1)
    ///
    /// The only difference from the legacy path is that normalization goes through
    /// [`normalize_output_with_shift`] instead of `normalize_output`. The two are
    /// byte-identical by contract (`normalize_output(input)` is a thin wrapper over
    /// `normalize_output_with_shift(input).0`), so the bytes written to `writer` are
    /// unchanged whether or not a sink is attached. When `sink` is `None` the
    /// producer seam is inert and the output equals the disabled (debug-off) output
    /// exactly.
    ///
    /// # Arguments
    /// * `file` - The parsed PastaFile AST
    /// * `writer` - Output writer
    /// * `sink` - Optional source-map recording sink (production loader attaches one)
    pub fn transpile_with_source_map<W: Write>(
        &self,
        file: &PastaFile,
        writer: &mut W,
        sink: Option<&mut dyn SourceMapSink>,
    ) -> Result<(TranspileContext, LineShift), TranspileError> {
        let mut context = TranspileContext::new();

        // Use intermediate buffer for code generation
        let mut intermediate_buffer: Vec<u8> = Vec::new();
        let mut codegen =
            LuaCodeGenerator::with_line_ending(&mut intermediate_buffer, self.config.line_ending);

        // Attach the source-map sink (producer side) when provided. When `None`, the
        // generator's seam stays inert and the output bytes are unchanged (7.1).
        if let Some(sink) = sink {
            codegen.set_source_map(sink);
        }

        // Write header
        codegen.write_header()?;

        // Process FileItems in document order (MAJOR-2)
        for item in &file.items {
            match item {
                FileItem::FileAttr(attr) => context.accumulate_file_attr(attr),
                FileItem::GlobalWord(word) => {
                    Self::process_global_word(&mut context, &mut codegen, word)?;
                }
                FileItem::GlobalSceneScope(scene) => {
                    Self::process_global_scene(&mut context, &mut codegen, scene)?;
                }
                FileItem::ActorScope(actor) => {
                    Self::process_actor(&mut context, &mut codegen, actor)?;
                }
            }
        }

        // Convert intermediate buffer to UTF-8 string and normalize. Use the
        // shift-returning normalize so the caller can rebase recorded pre-normalize
        // lines onto final `.lua` lines (2.1). `.0` is byte-identical to the legacy
        // `normalize_output`, so the bytes written below are unchanged (7.1).
        let raw_output = String::from_utf8(intermediate_buffer)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        let (normalized_output, shift) = normalize_output_with_shift(&raw_output);

        // Write normalized output to final writer
        writer.write_all(normalized_output.as_bytes())?;

        Ok((context, shift))
    }

    /// Process GlobalWord: register in WordDefRegistry and generate Lua code.
    fn process_global_word<W: Write>(
        context: &mut TranspileContext,
        codegen: &mut LuaCodeGenerator<W>,
        word: &KeyWords,
    ) -> Result<(), TranspileError> {
        for name in &word.names {
            context
                .word_registry
                .register_global(name, word.words.clone());
        }
        codegen.generate_global_word(word)?;
        Ok(())
    }

    /// Process GlobalSceneScope: register scene/words, merge attrs, generate code, register locals.
    fn process_global_scene<W: Write>(
        context: &mut TranspileContext,
        codegen: &mut LuaCodeGenerator<W>,
        scene: &GlobalSceneScope,
    ) -> Result<(), TranspileError> {
        let (_, counter) = context.register_global_scene(scene);

        // Register scene-level word definitions in WordDefRegistry
        let module_name = format!("{}{}", SceneRegistry::sanitize_name(&scene.name), counter);
        for kw in &scene.words {
            for name in &kw.names {
                context
                    .word_registry
                    .register_local(&module_name, name, kw.words.clone());
            }
        }

        // Merge file attrs with scene attrs, generate Lua code
        let merged_attrs = context.merge_attrs(&scene.attrs);
        codegen.generate_global_scene(scene, counter, context, &merged_attrs)?;

        // Register named local scenes (start scene is part of global)
        for (local_idx, local_scene) in scene.local_scenes.iter().enumerate() {
            if local_scene.name.is_some() {
                context.register_local_scene(local_scene, &scene.name, counter, local_idx + 1);
            }
        }

        Ok(())
    }

    /// Process ActorScope: register actor words and generate Lua code.
    fn process_actor<W: Write>(
        context: &mut TranspileContext,
        codegen: &mut LuaCodeGenerator<W>,
        actor: &ActorScope,
    ) -> Result<(), TranspileError> {
        for word_def in &actor.words {
            for name in &word_def.names {
                context
                    .word_registry
                    .register_actor(&actor.name, name, word_def.words.clone());
            }
        }
        codegen.generate_actor(actor)?;
        Ok(())
    }

    /// Get the transpiler configuration.
    pub fn config(&self) -> &TranspilerConfig {
        &self.config
    }
}

#[cfg(test)]
#[path = "transpiler_tests.rs"]
mod tests;
